# The domain the dashboard should be exposed on.
dashboard_domain: wikis.localhost
kits:
  # Must match the docker compose project name
  main:
    # The local domain the server should listen on.
    # If you're not using .localhost, you need to modify /etc/hosts
    domain: main.localhost
    # (Optional) The port to listen on.
    # Defaults to 80
    port: 80
    # (Optional) The name of the web container nginx should connect to.
    # Defaults to "{kit}-mediawiki-web-1"
    web-container: "main-mediawiki-web-1"
    # (Optional) Whether nginx should initially connect to this kit.
    # Defaults to false
    connect-initially: false
# (Optional) The refresh interval in seconds for docker event polling.
# Defaults to 5
docker-event-refresh-interval: 5
