services:
  orchestrator:
    container_name: mw-orchestrator
    build: .
    networks: [ mw-orchestrator-internal ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/:/app/nginx/
      - ./config.yml:/app/config.yml
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
  nginx:
    image: nginx:latest
    container_name: mw-orchestrator-nginx
    ports: [ "80:80" ]
    networks: [ mw-orchestrator-internal ]
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/static/:/static/:ro
    depends_on:
      orchestrator:
        condition: service_healthy

networks:
  mw-orchestrator-internal:
