services:
  orchestrator:
    container_name: mw-orchestrator
    build: .
    networks: [ mw-orchestrator-internal ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/:/app/nginx/
      - ./config.yml:/app/config.yml
  nginx:
    image: nginx:latest
    container_name: mw-orchestrator-nginx
    ports: [ "80:80" ]
    networks: [ mw-orchestrator-internal ]
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    depends_on:
      orchestrator:
        condition: service_healthy

networks:
  mw-orchestrator-internal:
